Repository DubBro/QuickNoteVault, pull requests merged in 2024-12, with the labels that each got.

#1 Added entities
  QuickNoteVault.API/QuickNoteVault.API.sln
  QuickNoteVault.API/QuickNoteVault.DAL/Entities/NoteEntity.cs
  QuickNoteVault.API/QuickNoteVault.DAL/Entities/UserEntity.cs
  QuickNoteVault.API/QuickNoteVault.DAL/QuickNoteVault.DAL.csproj
Labels: enhancement, good first issue

#5 QNV-57 QNV-33 Added DbInitializer. Several cosmetic corrections
  QuickNoteVault.API/QuickNoteVault.DAL/ApplicationDbContext.cs
  QuickNoteVault.API/QuickNoteVault.DAL/DbInitializer.cs
  QuickNoteVault.API/QuickNoteVault.DAL/Entities/NoteEntity.cs
  QuickNoteVault.API/QuickNoteVault.DAL/EntityConfigurations/NoteEntityTypeConfiguration.cs
  QuickNoteVault.API/QuickNoteVault.DAL/EntityConfigurations/UserEntityTypeConfiguration.cs
  QuickNoteVault.API/QuickNoteVault.DAL/Migrations/20241220194527_InitialCreate.Designer.cs
  QuickNoteVault.API/QuickNoteVault.DAL/Migrations/20241220194527_InitialCreate.cs
  QuickNoteVault.API/QuickNoteVault.DAL/Migrations/ApplicationDbContextModelSnapshot.cs
  QuickNoteVault.API/QuickNoteVault.DAL/Repository/IRepository.cs
  QuickNoteVault.API/QuickNoteVault.DAL/Repository/Repository.cs
  QuickNoteVault.API/QuickNoteVault.DAL/UOW/IUnitOfWork.cs
  QuickNoteVault.API/QuickNoteVault.DAL/UOW/UnitOfWork.cs
Labels: enhancement

#7 QNV-77 Created Infrastructure Layer
  QuickNoteVault.API/QuickNoteVault.API.sln
  QuickNoteVault.API/QuickNoteVault.API/QuickNoteVault.API.csproj
  QuickNoteVault.API/QuickNoteVault.BLL/QuickNoteVault.BLL.csproj
  QuickNoteVault.API/QuickNoteVault.Infrastructure/QuickNoteVault.Infrastructure.csproj
Labels: enhancement

#8 QNV-52 QNV-53 QNV-59 QNV-60 QNV-92 Created NoteService
  QuickNoteVault.API/QuickNoteVault.API/Program.cs
  QuickNoteVault.API/QuickNoteVault.API/QuickNoteVault.API.csproj
  QuickNoteVault.API/QuickNoteVault.BLL/BusinessLogicLayerExtensions.cs
  QuickNoteVault.API/QuickNoteVault.BLL/Models/NoteModel.cs
  QuickNoteVault.API/QuickNoteVault.BLL/Models/UserModel.cs
  QuickNoteVault.API/QuickNoteVault.BLL/QuickNoteVault.BLL.csproj
  QuickNoteVault.API/QuickNoteVault.BLL/Services/Interfaces/INoteService.cs
  QuickNoteVault.API/QuickNoteVault.BLL/Services/NoteService.cs
  QuickNoteVault.API/QuickNoteVault.BLL/Utils/Automapper/NoteProfile.cs
  QuickNoteVault.API/QuickNoteVault.Infrastructure/Exceptions/NoteNotFoundException.cs
  QuickNoteVault.API/QuickNoteVault.Infrastructure/Exceptions/UserNotFoundException.cs
  QuickNoteVault.API/QuickNoteVault.Infrastructure/QuickNoteVault.Infrastructure.csproj
Labels: enhancement

#9 QNV-93 QNV-94 QNV-95 QNV-96 QNV-97 Added NoteController
  QuickNoteVault.API/QuickNoteVault.API/Controllers/NoteController.cs
  QuickNoteVault.API/QuickNoteVault.API/DTOs/NoteDTO.cs
  QuickNoteVault.API/QuickNoteVault.API/DTOs/UserDTO.cs
  QuickNoteVault.API/QuickNoteVault.API/Program.cs
  QuickNoteVault.API/QuickNoteVault.API/QuickNoteVault.API.csproj
  QuickNoteVault.API/QuickNoteVault.API/Utils/Automapper/NoteProfile.cs
Labels: enhancement

#12 QNV-5 QNV-6 QNV-7 Created CI pipeline for API for development branch
  .github/workflows/api-ci-pipeline-development.yml
Labels: enhancement

#11 QNV-98 QNV-99 QNV-100 Implemented GetAll, Update, and Delete methods in NoteController
  QuickNoteVault.API/QuickNoteVault.API/Controllers/NoteController.cs
Labels: enhancement

#10 QNV-61 QNV-62 QNV-63 Implemented GetAllByUserId, Update, and Delete methods in NoteService
  QuickNoteVault.API/QuickNoteVault.BLL/Services/NoteService.cs
Labels: enhancement

#13 Changed order of launch profiles
  QuickNoteVault.API/QuickNoteVault.API/Properties/launchSettings.json
Labels: enhancement

#15 QNV-78 QNV-82 QNV-83 QNV-84 Created Unit Tests Layer
  QuickNoteVault.API/QuickNoteVault.API.sln
  QuickNoteVault.API/QuickNoteVault.UnitTests/QuickNoteVault.UnitTests.csproj
  QuickNoteVault.API/QuickNoteVault.UnitTests/Services/NoteServiceTests.cs
Labels: enhancement

#16 QNV-85 QNV-86 QNV-87 Created unit tests for `GetByIdAsync` and `AddAsync`
  QuickNoteVault.API/QuickNoteVault.API.sln
  QuickNoteVault.API/QuickNoteVault.UnitTests/QuickNoteVault.UnitTests.csproj
  QuickNoteVault.API/QuickNoteVault.UnitTests/Services/NoteServiceTests.cs
Labels: enhancement

#17 QNV-103 QNV-104 QNV-105 QNV-106 QNV-107 Added returning note Id after adding, updating, deleting it
  QuickNoteVault.API/QuickNoteVault.API/Controllers/NoteController.cs
  QuickNoteVault.API/QuickNoteVault.BLL/Services/Interfaces/INoteService.cs
  QuickNoteVault.API/QuickNoteVault.BLL/Services/NoteService.cs
  QuickNoteVault.API/QuickNoteVault.DAL/Repository/IRepository.cs
  QuickNoteVault.API/QuickNoteVault.DAL/Repository/Repository.cs
  QuickNoteVault.API/QuickNoteVault.UnitTests/Services/NoteServiceTests.cs
Labels: enhancement

#18 QNV-109 QNV-110 QNV-111 Improved API endpoints
  QuickNoteVault.API/QuickNoteVault.API/Controllers/NoteController.cs
  QuickNoteVault.API/QuickNoteVault.API/DTOs/Note/NoteAddItemDTO.cs
  QuickNoteVault.API/QuickNoteVault.API/DTOs/Note/NoteDTO.cs
  QuickNoteVault.API/QuickNoteVault.API/DTOs/Note/NoteListItemDTO.cs
  QuickNoteVault.API/QuickNoteVault.API/DTOs/Note/NoteUpdateItemDTO.cs
  QuickNoteVault.API/QuickNoteVault.API/DTOs/User/UserDTO.cs
  QuickNoteVault.API/QuickNoteVault.API/Utils/Automapper/NoteProfile.cs
Labels: enhancement

#19 QNV-71 Note page
  QuickNoteVault.client/.env.example
  QuickNoteVault.client/.husky/commit-msg
  QuickNoteVault.client/.husky/pre-commit
  QuickNoteVault.client/README.md
  QuickNoteVault.client/package.json
  QuickNoteVault.client/pnpm-lock.yaml
  QuickNoteVault.client/src/api/notes/queries.ts
  QuickNoteVault.client/src/api/notes/resources.ts
  QuickNoteVault.client/src/api/notes/types.ts
  QuickNoteVault.client/src/api/query-client.ts
  QuickNoteVault.client/src/api/shared/error/types.ts
  QuickNoteVault.client/src/components/editor/plate-editor.tsx
  QuickNoteVault.client/src/components/editor/use-create-editor.ts
  QuickNoteVault.client/src/components/page.tsx
  QuickNoteVault.client/src/components/plate-ui/editor.tsx
  QuickNoteVault.client/src/components/ui/button.tsx
  QuickNoteVault.client/src/components/ui/form.tsx
  QuickNoteVault.client/src/main.tsx
  QuickNoteVault.client/src/pages/add-note/page.tsx
  QuickNoteVault.client/src/pages/home/components/note-card.tsx
  QuickNoteVault.client/src/pages/home/components/note-filters.tsx
  QuickNoteVault.client/src/pages/home/page.tsx
  QuickNoteVault.client/src/pages/note/loader.ts
  QuickNoteVault.client/src/pages/note/page.tsx
  QuickNoteVault.client/src/router.tsx
  QuickNoteVault.client/tailwind.config.js
Labels: enhancement

#20 QNV-102 Created CI pipeline for client for development branch
  .github/workflows/api-ci-pipeline-development.yml
  .github/workflows/client-ci-pipeline-development.yml
Labels: enhancement

#23 QNV-12 Remove note functionality
  QuickNoteVault.client/index.html
  QuickNoteVault.client/src/api/notes/queries.ts
  QuickNoteVault.client/src/components/app-sidebar/app-sidebar.tsx
  QuickNoteVault.client/src/components/plate-ui/excalidraw-element.tsx
  QuickNoteVault.client/src/components/plate-ui/export-toolbar-button.tsx
  QuickNoteVault.client/src/components/plate-ui/floating-toolbar.tsx
  QuickNoteVault.client/src/components/plate-ui/heading-element.tsx
  QuickNoteVault.client/src/components/plate-ui/highlight-leaf.tsx
  QuickNoteVault.client/src/components/plate-ui/hr-element.tsx
  QuickNoteVault.client/src/components/plate-ui/image-element.tsx
  QuickNoteVault.client/src/components/plate-ui/indent-list-toolbar-button.tsx
  QuickNoteVault.client/src/components/plate-ui/indent-toolbar-button.tsx
  QuickNoteVault.client/src/components/plate-ui/kbd-leaf.tsx
  QuickNoteVault.client/src/components/plate-ui/line-height-dropdown-menu.tsx
  QuickNoteVault.client/src/components/plate-ui/link-element.tsx
  QuickNoteVault.client/src/components/plate-ui/link-floating-toolbar.tsx
  QuickNoteVault.client/src/components/plate-ui/link-toolbar-button.tsx
  QuickNoteVault.client/src/components/plate-ui/mark-toolbar-button.tsx
  QuickNoteVault.client/src/components/plate-ui/media-audio-element.tsx
  QuickNoteVault.client/src/components/plate-ui/media-embed-element.tsx
  QuickNoteVault.client/src/components/plate-ui/media-file-element.tsx
  QuickNoteVault.client/src/components/plate-ui/media-video-element.tsx
  QuickNoteVault.client/src/components/plate-ui/mention-element.tsx
  QuickNoteVault.client/src/components/plate-ui/mode-dropdown-menu.tsx
  QuickNoteVault.client/src/components/plate-ui/more-dropdown-menu.tsx
  QuickNoteVault.client/src/components/plate-ui/outdent-toolbar-button.tsx
  QuickNoteVault.client/src/components/plate-ui/paragraph-element.tsx
  QuickNoteVault.client/src/components/plate-ui/resizable.tsx
  QuickNoteVault.client/src/components/plate-ui/spinner.tsx
  QuickNoteVault.client/src/components/plate-ui/table-dropdown-menu.tsx
  QuickNoteVault.client/src/components/plate-ui/table-row-element.tsx
  QuickNoteVault.client/src/components/plate-ui/toggle-toolbar-button.tsx
  QuickNoteVault.client/src/components/remove-note-dialog.tsx
  QuickNoteVault.client/src/components/ui/dialog.tsx
  QuickNoteVault.client/src/components/ui/dropdown-menu.tsx
  QuickNoteVault.client/src/pages/home/components/note-card/components/note-menu.tsx
  QuickNoteVault.client/src/pages/home/components/note-card/note-card.tsx
  QuickNoteVault.client/src/pages/home/page.tsx
  QuickNoteVault.client/src/pages/note/components/delete-note.tsx
  QuickNoteVault.client/src/pages/note/loader.ts
  QuickNoteVault.client/src/pages/note/page.tsx
  QuickNoteVault.client/src/routes.ts
Labels: enhancement

#24 QNV-113 Edit note functionality
  QuickNoteVault.client/package.json
  QuickNoteVault.client/pnpm-lock.yaml
  QuickNoteVault.client/src/api/notes/resources.ts
  QuickNoteVault.client/src/api/notes/types.ts
  QuickNoteVault.client/src/api/query-client.ts
  QuickNoteVault.client/src/pages/note/page.tsx
Labels: enhancement

#22 QNV-89 QNV-90 QNV-91 Created unit tests for GetAllByUserIdAsync, UpdateAsync and DeleteByIdAsync
  QuickNoteVault.API/QuickNoteVault.UnitTests/Services/NoteServiceTests.cs
Labels: enhancement

#26 QNV-46 QNV-47 QNV-48 QNV-49 Added README files
  QuickNoteVault.API/README.md
  QuickNoteVault.client/README.md
  README.md
Labels: documentation

#30 #29 Improved static code analysis for API
  QuickNoteVault.API/.editorconfig
  QuickNoteVault.API/Directory.Build.props
  QuickNoteVault.API/QuickNoteVault.API.sln
  QuickNoteVault.API/QuickNoteVault.API/Controllers/NoteController.cs
  QuickNoteVault.API/QuickNoteVault.API/Program.cs
  QuickNoteVault.API/QuickNoteVault.API/QuickNoteVault.API.csproj
  QuickNoteVault.API/QuickNoteVault.BLL/BusinessLogicLayerExtensions.cs
  QuickNoteVault.API/QuickNoteVault.BLL/QuickNoteVault.BLL.csproj
  QuickNoteVault.API/QuickNoteVault.DAL/QuickNoteVault.DAL.csproj
  QuickNoteVault.API/QuickNoteVault.Infrastructure/QuickNoteVault.Infrastructure.csproj
  QuickNoteVault.API/QuickNoteVault.UnitTests/QuickNoteVault.UnitTests.csproj
  QuickNoteVault.API/settings.ruleset
Labels: enhancement
